name: CI Pipeline

on:
  pull_request:
    branches: [main]
  push:
    branches: [main]

jobs:
  deploy-cloud-run:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read

    steps:
    - name: Checkout code
      uses: actions/checkout@v3
      with:
        fetch-depth: 0

    - name: Set up Python environment
      uses: actions/setup-python@v4
      with:
        python-version: '3.12.7' # Ensures consistency with development

    - name: Install dependencies
      run: |
        pip install -r requirements.txt
        pip install -r requirements-dev.txt

    - name: Run tests with coverage
      run: pytest --cov=name -n auto

    - name: Upload coverage report to Codecov
      uses: codecov/codecov-action@v3
      with:
        token: ${{ secrets.CODECOV_TOKEN }}

    - name: Snyk Security Scan
      uses: snyk/actions/python@master
      env:
        SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}

    - name: Log in to GitHub Container Registry
      uses: docker/login-action@v3
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ secrets.TOKEN }}

    - name: Build Docker image
      run: docker build -t ghcr.io/${{ github.repository }}:latest .

    - name: Push Docker image to GitHub Container Registry
      run: docker push ghcr.io/${{ github.repository }}:latest

    - name: Authenticate with Service Account Key
      env:
        GOOGLE_APPLICATION_CREDENTIALS: ${{ secrets.GCP_SA_KEY }}
      run: |
        echo "${{ secrets.GCP_SA_KEY }}" > "${HOME}/gcp-key.json"
        gcloud auth activate-service-account --key-file="${HOME}/gcp-key.json"
        gcloud config set project <your-project-id>

    - name: Deploy to Cloud Run
      run: |
        gcloud run deploy note-api-${{ github.repository_owner }} \
          --image ghcr.io/${{ github.repository }}:latest \
          --region europe-west3 \
          --platform managed \
          --update-env-vars BACKEND=memory

    - name: Validate deployment
      run: curl "$(gcloud run services describe note-api-${{ github.repository_owner }} --region europe-west3 --format 'value(status.url)')"
